# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1Bz-yd9SCKVdqj1ZGbcb3NQXjfEIP5u
"""

pip install altair pandas

import altair as alt
import pandas as pd

# Load the dataset
data = pd.read_csv('/content/penglings.csv')

# Create the scatter plot
chart = alt.Chart(data).mark_circle(opacity=0.8).encode(
    x=alt.X('flipper_length_mm:Q', scale=alt.Scale(zero=False), title='Flipper Length (mm)'),
    y=alt.Y('body_mass_g:Q', scale=alt.Scale(zero=False), title='Body Mass (g)'),
    color='species:N',
    size=alt.Size('bill_length_mm:Q', scale=alt.Scale(range=[0, 1000]), title='Bill Length (mm)')
).properties(
    title='Penguin Scatterplot'
)

# Display the chart
chart