# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13W8M3ijXYdOrkiJqhPApqc9fYBOZsVMn
"""

# Load required libraries
library(ggplot2)

# Assuming your data is loaded into a data frame called 'penguins'
penguins <- read.csv("/content/penglings.csv")

# Create the scatterplot
ggplot(penguins, aes(x = FlipperLength, y = BodyMass, color = Species, size = BillLength)) +
  geom_point(alpha = 0.8) +  # Set the transparency
  scale_x_continuous(limits = c(170, 230), breaks = seq(170, 230, by = 10)) +  # Adjust x-axis
  scale_y_continuous(limits = c(3000, 6000), breaks = seq(3000, 6000, by = 500)) +  # Adjust y-axis
  theme_minimal() +  # Apply a minimal theme
  theme(legend.position = "none") +  # Remove the legend, if not required
  labs(x = "Flipper Length (mm)", y = "Body Mass (g)")  # Label the axes

# Load required libraries
library(ggplot2)

# Load the data into a data frame called 'penguins'
penguins <- read.csv("/content/penglings.csv")

# Create the scatterplot
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species, size = bill_length_mm)) +
  geom_point(alpha = 0.8) +  # Set the transparency
  scale_x_continuous(limits = c(170, 230), breaks = seq(170, 230, by = 10)) +  # Adjust x-axis
  scale_y_continuous(limits = c(3000, 6000), breaks = seq(3000, 6000, by = 500)) +  # Adjust y-axis
  theme_minimal() +  # Apply a minimal theme
  theme(legend.position = "none") +  # Remove the legend, if not required
  labs(x = "Flipper Length (mm)", y = "Body Mass (g)")  # Label the axes

# Load required libraries
library(ggplot2)
library(dplyr) # for data manipulation

# Load the data into a data frame called 'penguins'
penguins <- read.csv("/content/penglings.csv")

# Inspect missing values
sum(is.na(penguins$flipper_length_mm))
sum(is.na(penguins$body_mass_g))
sum(is.na(penguins$species))
sum(is.na(penguins$bill_length_mm))

# Optionally, remove rows with missing values
penguins <- na.omit(penguins)

# Create the scatterplot
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species, size = bill_length_mm)) +
  geom_point(alpha = 0.8) +  # Set the transparency
  scale_x_continuous(limits = c(170, 230), breaks = seq(170, 230, by = 10)) +  # Adjust x-axis
  scale_y_continuous(limits = c(3000, 6000), breaks = seq(3000, 6000, by = 500)) +  # Adjust y-axis
  theme_minimal() +  # Apply a minimal theme
  theme(legend.position = "none") +  # Remove the legend, if not required
  labs(x = "Flipper Length (mm)", y = "Body Mass (g)")  # Label the axes

# Load required libraries
library(ggplot2)
library(dplyr) # for data manipulation

# Load the data into a data frame called 'penguins'
penguins <- read.csv("/content/penglings.csv")

# Inspect missing values
sum(is.na(penguins$flipper_length_mm))
sum(is.na(penguins$body_mass_g))
sum(is.na(penguins$species))
sum(is.na(penguins$bill_length_mm))

# Remove rows with missing values
penguins <- na.omit(penguins)

# Expand the limits to include all data points or remove the limits to let ggplot2 decide
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species, size = bill_length_mm)) +
  geom_point(alpha = 0.8) +  # Set the transparency
  theme_minimal() +  # Apply a minimal theme
  theme(legend.position = "none") +  # Remove the legend, if not required
  labs(x = "Flipper Length (mm)", y = "Body Mass (g)")  # Label the axes