---
title: "R_with_plotly"
output: html_notebook
---
*# **R Extension for VS Code:**
 https://marketplace.visualstudio.com/items?itemName=REditorSupport.r
 
 
 
```{r}
install.packages("htmltools", type = "source")
```

```{r}
# Install plotly package
install.packages("plotly")
```

```{r}
#read file penglings.csv
penglings <- read.csv("penglings.csv")

# Display the first few rows of the data
head(penglings)
```
```{r}
# Normalize and scale bill length that will be used to create scatterplots
min_bill_length <- min(penglings$bill_length_mm, na.rm = TRUE)
max_bill_length <- max(penglings$bill_length_mm, na.rm = TRUE)
penglings$scaled_sizes <- (penglings$bill_length_mm - min_bill_length) / (max_bill_length - min_bill_length)
penglings$scaled_sizes <- penglings$scaled_sizes * 4 + 1
```


```{r}
#load plotly package
library(plotly)
```
```{r}
# Create a scatter plot using Plotly
scatter_plot <- plot_ly(data = penglings, x = ~flipper_length_mm, y = ~body_mass_g, type = "scatter", mode = "markers",
                        color = ~species, size = ~scaled_sizes, colors = c("darkorange", "darkgreen", "purple")) %>%
    layout(title = "Scatter Plot of Penguins: Flipper Length vs Body Mass",
           xaxis = list(title = "Flipper Length (mm)"),
           yaxis = list(title = "Body Mass (g)"),
           legend = list(title = "Species"),
           showlegend = TRUE,
           legend = list(x = 1.1, y = 1)) %>%
    add_markers(alpha = 0.8)

# Display the scatter plot
scatter_plot
```
