---
title: "R_with_ggplot2"
output: html_notebook
---
*# **R Extension for VS Code:**
 https://marketplace.visualstudio.com/items?itemName=REditorSupport.r

```{r}
# Install ggplot2 package
install.packages("ggplot2")
```

```{r}
#read file penglings.csv
penglings <- read.csv("penglings.csv")

# Display the first few rows of the data
head(penglings)
```
```{r}
# Normalize and scale bill length that will be used to create scatterplots
min_bill_length <- min(penglings$bill_length_mm, na.rm = TRUE)
max_bill_length <- max(penglings$bill_length_mm, na.rm = TRUE)
penglings$scaled_sizes <- (penglings$bill_length_mm - min_bill_length) / (max_bill_length - min_bill_length)
penglings$scaled_sizes <- penglings$scaled_sizes * 4 + 1
```


```{r}
#load ggplot2 package
library(ggplot2)

# Create a scatter plot of the data
ggplot(
    penglings, 
    aes(x = flipper_length_mm, y=body_mass_g,
        color = species,
        size = scaled_sizes)) +
    geom_point(alpha=0.8) + # Set transparency to 0.8
    scale_color_manual(values=c("Adelie" = "darkorange", "Gentoo"="dark green", 
                            "Chinstrap" = "purple")) +
    scale_size_continuous(range=c(2, 10)) +   # Set size range for points 
    labs(title="Scatter Plot of Penguins: Flipper Length vs Body Mass",
                x="Flipper Length (mm)", y="Body Mass (g)") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(legend.position="right") +
guides(color=guide_legend(title="Species"), size=FALSE) +
    coord_fixed(ratio = 1/100) # Adjust aspect ratio such that X axis is 100 times the Y axis
```
